name: Prerelease

on:
  push:
    branches: [ "develop" ]

jobs:
  update-changelog:

    # This stops the workflow running recursively when we push the updated changelog
    if: github.event.head_commit.message != 'Update CHANGELOG'

    runs-on: windows-2022
    name: Construct Version
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.PAT }}
          fetch-depth: 0

      - name: Calculate Version String
        id: version
        uses: paulhatch/semantic-version@v4.0.2
        with:
          tag_prefix: "v"
          major_pattern: "(MAJOR)"
          minor_pattern: "(MINOR)"
          format: "${major}.${minor}.${patch}"
          bump_each_commit: false
    
      - name: Update changelog
        uses: thomaseizinger/keep-a-changelog-new-release@v1
        with:
          version: ${{ steps.version.outputs.version }}

      - name: Commit updated CHANGELOG
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Update CHANGELOG
          file_pattern: CHANGELOG.md
          commit_user_name: workflows-bot